version: '3.9'
services:
  #keycloak

  nl-portal-keycloak:
      container_name: nl-portal-keycloak
      hostname: keycloak.nlportal.local
      depends_on:
          - nl-portal-keycloak-database
      image: quay.io/keycloak/keycloak:24.0.1
      ports:
          - "8080:8080"
      environment:
          KEYCLOAK_ADMIN: admin
          KEYCLOAK_ADMIN_PASSWORD: admin
          KC_DB: postgres
          KC_DB_URL: jdbc:postgresql://nl-portal-keycloak-database/keycloak
          KC_DB_USERNAME: keycloak
          KC_DB_PASSWORD: keycloak
          KC_FEATURES: token-exchange,admin-fine-grained-authz
          KC_HTTP_RELATIVE_PATH: /auth
      volumes:
          - ./imports/keycloak-portal:/opt/keycloak/data/import
      command: "start-dev --import-realm"

  nl-portal-keycloak-database:
      image: postgres:14.1
      container_name: nl-portal-keycloak-database
      environment:
          POSTGRES_USER: keycloak
          POSTGRES_PASSWORD: keycloak

  #nl portal database
  nl-portal-database:
      container_name: nl-portal-database
      image: postgres:14.1
      ports:
          - "54321:5432"
      environment:
          POSTGRES_USER: nlportal
          POSTGRES_PASSWORD: password
          POSTGRES_DB: nl-portal
      volumes:
          - nl-portal-database-data:/var/lib/postgres # persist data even if container shuts down

  #zgw
  nl-portal-openzaak:
      image: openzaak/open-zaak:1.8.1
      container_name: nl-portal-openzaak
      platform: linux/amd64
      profiles:
          - zgw
          - openzaak
      environment:
          - DB_HOST=nl-portal-openzaak-database
          - DB_POST=5433
          - SECRET_KEY=veryRestrictedSecretKey
          - DB_USER=openzaak
          - DB_PASSWORD=openzaak
          - DB_NAME=openzaak
          - CACHE_DEFAULT=nl-portal-redis:6379/0
          - CACHE_AXES=nl-portal-redis:6379/0
          - DEBUG=true
          - ALLOWED_HOSTS=localhost,host.docker.internal,172.17.0.1,openzaak,nl-portal-openzaak
          - OPENZAAK_SUPERUSER_USERNAME=admin
          - OPENZAAK_SUPERUSER_EMAIL=admin@admin.org
          - DJANGO_SUPERUSER_PASSWORD=admin
          - SENDFILE_BACKEND=django_sendfile.backends.simple
      ports:
          - "8001:8000"
      depends_on:
          -   nl-portal-openzaak-database
          -   nl-portal-redis

  nl-portal-openzaak-database:
      image: mdillon/postgis:11
      container_name: nl-portal-openzaak-database
      platform: linux/amd64
      profiles:
          - zgw
          - openzaak
      environment:
          - POSTGRES_USER=openzaak
          - POSTGRES_PASSWORD=openzaak
          - POSTGRES_DB=openzaak
      volumes:
          - ./imports/open-zaak:/docker-entrypoint-initdb.d

  nl-portal-openklant:
      image: maykinmedia/open-klant:0.1
      container_name: nl-portal-openklant
      platform: linux/amd64
      profiles:
          - zgw
          - openklant
      environment:
          - DB_HOST=nl-portal-openklant-database
          - SECRET_KEY=veryRestrictedSecretKey
          - DB_USER=openklant
          - DB_PASSWORD=openklant
          - DB_NAME=openklant
          - CACHE_DEFAULT=nl-portal-redis:6379/0
          - CACHE_AXES=nl-portal-redis:6379/0
          - ALLOWED_HOSTS=*
          - DJANGO_SETTINGS_MODULE=openklant.conf.docker
      ports:
          - "8006:8000"
      depends_on:
          -   nl-portal-openklant-database
          -   nl-portal-redis
  nl-portal-openklant-database:
      image: mdillon/postgis:11
      container_name: nl-portal-openklant-database
      platform: linux/amd64
      profiles:
          - zgw
          - openklant
      environment:
          - POSTGRES_USER=openklant
          - POSTGRES_PASSWORD=openklant
          - POSTGRES_DB=openklant
      volumes:
          - ./imports/open-klant:/docker-entrypoint-initdb.d

  nl-portal-redis:
      image: redis:6.2.6
      container_name: nl-portal-redis
      profiles:
          - zgw
          - openklant

  nl-portal-objecten-api:
      image: maykinmedia/objects-api:2.1.1
      container_name: nl-portal-objecten-api
      platform: linux/amd64
      profiles:
          - zgw
          - objecten
      ports:
          - "8010:8000"
      environment: &objects-env
          - CORS_ALLOW_ALL_ORIGINS=true
          - SECRET_KEY=${SECRET_KEY:-1(@f(-6s_u(5fd&1sg^uvu2s(c-9sapw)1era8q&)g)h@cwxxg}
          - DJANGO_SETTINGS_MODULE=objects.conf.docker
          - DB_HOST=nl-portal-objecten-api-database
          - DEBUG=true
          - TWO_FACTOR_FORCE_OTP_ADMIN=False # this is not available yet in this version
          - TWO_FACTOR_PATCH_ADMIN=False
      depends_on:
          - nl-portal-objecten-api-database

  nl-portal-objecten-api-database:
      image: postgis/postgis:13-3.1
      container_name: nl-portal-objecten-api-database
      platform: linux/amd64
      profiles:
          - zgw
          - objecten
      environment:
          - POSTGRES_USER=objects
          - POSTGRES_PASSWORD=objects
          - POSTGRES_DB=objects

  nl-portal-objecten-api-import:
      image: maykinmedia/objects-api:2.1.1
      container_name: nl-portal-objects-api-import
      platform: linux/amd64
      profiles:
          - zgw
          - objecten
      environment: *objects-env
      # in the current version of django it is not possible to create a new user with password without user interaction by using the createsuperuser command
      command: sh init/init.sh
      volumes:
          - ./imports/objects-api/fixtures:/app/src/objects/fixtures
          - ./imports/objects-api/init:/app/init
      depends_on:
          - nl-portal-objecten-api

  nl-portal-objecttypen-api:
      image: maykinmedia/objecttypes-api:2.1.0
      container_name: nl-portal-objecttypen-api
      platform: linux/amd64
      profiles:
          - zgw
          - objecten
      ports:
          - "8011:8000"
      environment: &objecttypes-env
          - CORS_ALLOW_ALL_ORIGINS=true
          - SECRET_KEY=${SECRET_KEY:-fgv=c0hz&tl*8*3m3893@m+1pstrvidc9e^5@fpspmg%cy$$15d}
          - DJANGO_SETTINGS_MODULE=objecttypes.conf.docker
          - DB_HOST=nl-portal-objecttypen-api-database
          - DEBUG=true
          - TWO_FACTOR_FORCE_OTP_ADMIN=False # this is not available yet in this version
          - TWO_FACTOR_PATCH_ADMIN=False
      depends_on:
          - nl-portal-objecttypen-api-database

  nl-portal-objecttypen-api-database:
        image: postgres:14.1
        container_name: nl-portal-objecttypen-api-database
        profiles:
            - zgw
            - objecten
        environment:
            - POSTGRES_USER=objecttypes
            - POSTGRES_PASSWORD=objecttypes
            - POSTGRES_DB=objecttypes


  nl-portal-objecttypen-api-import:
      image: maykinmedia/objecttypes-api:2.1.0
      container_name: nl-portal-objecttypen-api-import
      platform: linux/amd64
      profiles:
          - zgw
          - objecten
      environment: *objecttypes-env
      command: sh init/init.sh
      volumes:
          - ./imports/objecttypes-api/fixtures:/app/src/objecttypes/fixtures
          - ./imports/objecttypes-api/init:/app/init
      depends_on:
          - nl-portal-objecttypen-api


  # Open notificaties
  nl-portal-open-notificaties-rabbitmq:
      image: rabbitmq:3.9-management
      container_name: nl-portal-open-notificaties-rabbitmq
      expose:
          - 5673
          - 15673
      ports:
          - "5673:5673"
          - "15673:15673"

  nl-portal-open-notificaties:
      image: openzaak/open-notificaties:1.4.3
      container_name: nl-portal-open-notificaties
      platform: linux/amd64
      ports:
          - "8002:8000"
      environment: &notificaties-env
          - DJANGO_SETTINGS_MODULE=nrc.conf.docker
          - SECRET_KEY=${SECRET_KEY:-4wHY2Cp5`4(q%)]cuWxPQJRp5kN?g+`.Xah>%6Fsq6+)R>p_}
          - ALLOWED_HOSTS=*
          - CACHE_DEFAULT=nl-portal-redis-open-notificaties:6379/0
          - CACHE_AXES=nl-portal-redis-open-notificaties:6379/1
          - DB_PORT=5432
          - DB_HOST=nl-portal-database-open-notificaties
          - DB_NAME=notifications
          - DB_USER=notifications
          - DB_PASSWORD=notifications
          - DEBUG=true
          - RABBITMQ_HOST=nl-portal-open-notificaties-rabbitmq
          - PUBLISH_BROKER_URL=nl-portal-redis://nl-portal-redis-open-notificaties:6379/0
          - CELERY_BROKER_URL=nl-portal-redis://nl-portal-redis-open-notificaties:6379/0
          - CELERY_RESULT_BACKEND=nl-portal-redis://nl-portal-redis-open-notificaties:6379/0
          - CELERY_LOGLEVEL=DEBUG
          - CELERY_WORKER_CONCURRENCY=${CELERY_WORKER_CONCURRENCY:-4}

  nl-portal-open-notificaties-celery:
      image: openzaak/open-notificaties:1.4.3
      container_name: nl-portal-open-notificaties-celery
      platform: linux/amd64
      environment: *notificaties-env
      command: /celery_worker.sh

  nl-portal-database-open-notificaties:
      image: postgres:13.5  # open-notificaties doesn't work with postgres 14.
      container_name: nl-portal-database-open-notificaties
      ports:
          - "54319:5432"
      environment:
          - POSTGRES_USER=${DB_USER:-notifications}
          - POSTGRES_PASSWORD=${DB_PASSWORD:-notifications}
          - POSTGRES_DB=notifications
      volumes:
          - ./imports/open-notificaties:/docker-entrypoint-initdb.d

  nl-portal-redis-open-notificaties:
      image: redis:6.2.6
      container_name: nl-portal-redis-open-notificaties

  nl-portal-backendtemplate:
    
    build: 
      context: .
      dockerfile: portalbackendtemplate/Dockerfile
    healthcheck:
      test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit 1"
      interval: 2s
      timeout: 3s
      retries: 10
      start_period: 2s
    environment:
      - spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak.nlportal.local:8082/auth/realms/nlportal
    depends_on:
      - nl-portal-database
    profiles:
      - zgw
      - portal
    ports:
    - "8004:8090"


  nl-portal-frontendtemplate:
    build: 
      context: .
      dockerfile: portalfrontendtemplate/Dockerfile
    depends_on:
      - nl-portal-keycloak
      - nl-portal-backendtemplate
    profiles:
      - zgw
      - portal
    ports:
    - "3000:3000"

  gzac-frontendtemplate:
    build: 
      context: .
      dockerfile: gzacfrontendtemplate/Dockerfile
    depends_on:
      - gzac-keycloak
      - gzac-backendtemplate
    profiles:
      - zgw
      - gzac
    ports:
    - "4200:4200"

  gzac-backendtemplate:
    hostname: gzac.local
    build: 
      context: .
      dockerfile: gzacbackendtemplate/Dockerfile
    healthcheck:
      test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit 1"
      interval: 2s
      timeout: 3s
      retries: 10
      start_period: 2s
    profiles:
      - zgw
      - gzac
    depends_on:
      - gzac-database
    ports:
      - "8005:8080"

  gzac-keycloak:
      container_name: gzac-keycloak
      hostname: keycloak.gzac.local
      depends_on:
          - gzac-keycloak-database
      image: quay.io/keycloak/keycloak:24.0.1
      ports:
          - "8081:8080"
      environment:
          KEYCLOAK_ADMIN: admin
          KEYCLOAK_ADMIN_PASSWORD: admin
          KC_DB: postgres
          KC_DB_URL: jdbc:postgresql://gzac-keycloak-database/keycloak
          KC_DB_USERNAME: keycloak
          KC_DB_PASSWORD: keycloak
          KC_FEATURES: token-exchange,admin-fine-grained-authz
          KC_HTTP_RELATIVE_PATH: /auth
      volumes:
          - ./imports/keycloak-gzac:/opt/keycloak/data/import
      profiles:
        - zgw
        - gzac
      command: "start-dev --import-realm"


  gzac-keycloak-database:
      image: postgres:14.1
      container_name: gzac-keycloak-database
      ports:
          - "54329:5432"
      profiles:
        - zgw
        - gzac
      environment:
          POSTGRES_USER: keycloak
          POSTGRES_PASSWORD: keycloak

  gzac-database:
      container_name: gzac-database
      image: postgres:14.1
      ports:
          - "54320:5432"
      environment:
          POSTGRES_USER: gzac
          POSTGRES_PASSWORD: password
          POSTGRES_DB: gzac
      profiles:
        - zgw
        - gzac
      volumes:
          - gzac-database-data:/var/lib/postgres # persist data even if container shuts down

  gzac-rabbitmq:
      image: rabbitmq:3-management
      container_name: gzac-rabbitmq
      volumes:
          - ./imports/gzac-rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
          - ./imports/gzac-rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
      ports:
          - "5672:5672"
          - "15672:15672"
      profiles:
        - zgw 
        - gzac
volumes:
  nl-portal-database-data:
  gzac-database-data: